contacts/urls.py
from django.conf.urls import include, url

from .views import (
    book_views,
    contact_views,
    contact_list_views,
    import_views,
    log_views,
)

from .api import views as contact_api_views

contact_urls = [
    url(
        r'^contacts/$',
        contact_list_views.ContactListView.as_view(),
        name='contacts-list',
    ),
    url(
        r'^(?P<pk>\d+)/$',
        contact_views.ContactView.as_view(),
        name='contacts-view',
    ),
    url(
        r'^new$',
        contact_views.CreateContactView.as_view(),
        name='contacts-new',
    ),
    url(
        r'^edit/(?P<pk>\d+)/$',
        contact_views.EditContactView.as_view(),
        name='contacts-edit',
    ),
    url(
        r'^(?P<pk>\d+)/copy/$',
        contact_views.CopyContactView.as_view(),
        name='contacts-copy',
    ),
    url(
        r'^delete/(?P<pk>\d+)/$',
        contact_views.DeleteContactView.as_view(),
        name='contacts-delete',
    ),
    url(
        r'^tagged/(?P<pk>\d+)/$',
        contact_list_views.TaggedContactListView.as_view(),
        name='contacts-tagged',
    ),
    url(
        r'^search/',
        contact_list_views.ContactListView.as_view(),
        name="search",
    ),
    url(
        r'^emails/',
        contact_views.ExportEmailView.as_view(),
        name='contact_emails',
    ),
    url(
        r'^emailexport/',
        contact_views.email_csv_view,
        name='contact_email_export',
    ),
    url(
        r'^addresses/',
        contact_views.ExportAddressView.as_view(),
        name='contact_addresses',
    ),
    url(
        r'^addressexport/',
        contact_views.address_csv_view,
        name='contact_address_export',
    ),
    url(
        r'^fullexport/',
        contact_views.export_full_contact_book_json_view,
        name="fullexport",
    ),
    url(
        r'^merge/',
        contact_views.MergeContactsView.as_view(),
        name="contacts_merge",
    ),
    url(
        r'^addtag/',
        contact_views.AddTagView.as_view(),
        name="contacts_add_tag",
    ),
    url(
        r'^settings/',
        book_views.BookSettingsView.as_view(),
        name="book_settings",
    ),
]

tag_urls = [
    url(
        r'^new$',
        contact_views.CreateTagView.as_view(),
        name='tags-new',
    ),
    url(
        r'^(?P<pk>\d+)/edit/$',
        contact_views.EditTagView.as_view(),
        name='tags-edit',
    ),
    url(
        r'^(?P<pk>\d+)/delete/$',
        contact_views.DeleteTagView.as_view(),
        name='tags-delete',
    ),
    url(
        r'^(?P<tag>\d+)/emails/',
        contact_views.ExportEmailView.as_view(),
        name='tag_emails',
    ),
    url(
        r'^(?P<tag>\d+)/emailexport/',
        contact_views.email_csv_view,
        name='tag_emails_export',
    ),
    url(
        r'^(?P<tag>\d+)/addresses/',
        contact_views.ExportAddressView.as_view(),
        name='tag_addresses',
    ),
    url(
        r'^(?P<tag>\d+)/addressexport/',
        contact_views.address_csv_view,
        name='tag_address_export',
    ),
]

log_urls = [
    url(
        r'^edit/(?P<pk>\d+)/$',
        log_views.EditLogView.as_view(),
        name='log-edit',
    ),
    url(
        r'^delete/(?P<pk>\d+)/$',
        log_views.DeleteLogView.as_view(),
        name='log-delete',
    ),
    url(r'^$', log_views.LogListView.as_view(), name='log-list'),
]

api_urls = [
    url(
        r'^contacts/$',
        contact_api_views.ContactListCreateAPIView.as_view(),
    ),
    url(
        r'^contacts/(?P<pk>\d+)/$',
        contact_api_views.ContactDetailEditAPIView.as_view(),
    ),
    url(
        r'^contacts/(?P<pk>\d+)/logs/$',
        contact_api_views.LogListCreateAPIView.as_view(),
    ),
    url(
        r'^contacts/(?P<pk>\d+)/fields/$',
        contact_api_views.FieldListCreateAPIView.as_view(),
    ),
    url(r'^tags/$', contact_api_views.TagListCreateAPIView.as_view()),
]

reminder_urls = [
    url(r'^daily/$', contact_list_views.DailyRemindersView.as_view(), name="reminders-daily"),
    url(r'^weekly/$', contact_list_views.WeeklyRemindersView.as_view(), name="reminders-weekly"),
    url(r'^monthly/$', contact_list_views.MonthlyRemindersView.as_view(), name="reminders-monthly"),
    url(r'^quarterly/$', contact_list_views.QuarterlyRemindersView.as_view(), name="reminders-quarterly"),
]

logtacts/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView


# Why are we doing this crazy thing of spelling out all the allauth urls?
# Because I want to know _exactly_ what the surface area of the product is.
from allauth.account import views as allauth_views
from allauth.socialaccount import views as social_views
from allauth.socialaccount.providers.twitter import views as twitter_views
from allauth.socialaccount.providers.foursquare import views as foursquare_views
from allauth.socialaccount.providers.google import views as google_views

import nexus
import gargoyle

from contacts.urls import (
    api_urls,
    contact_urls,
    log_urls,
    reminder_urls,
    tag_urls,
)

from contacts.views import import_views
from contacts.views.log_views import email_log_view

from invitations.views import (
    CreateInviteView,
    AcceptInviteView,
)

from logtacts.views import HomeView
from payments.views import (
    PaymentView,
    stripe_webhook_view,
)
from chats.views import sms

admin.autodiscover()
gargoyle.autodiscover()


foursquare_urls = [
    url('^login/$', foursquare_views.oauth2_login, name="foursquare_login"),
    url(
        '^login/callback/$',
        foursquare_views.oauth2_callback,
        name="foursquare_callback",
    ),
]


twitter_urls = [
    url('^login/$', twitter_views.oauth_login, name="twitter_login"),
    url(
        '^login/callback/$',
        twitter_views.oauth_callback,
        name="twitter_callback",
    ),
]

google_urls = [
    url('^login/$', google_views.oauth2_login, name="google_login"),
    url(
        '^login/callback/$',
        google_views.oauth2_callback,
        name="google_callback",
    ),
]


social_urls = [
    url('^login/cancelled/$', social_views.login_cancelled,
        name='socialaccount_login_cancelled'),
    url('^login/error/$', social_views.login_error, name='socialaccount_login_error'),
    url('^signup/$', social_views.signup, name='socialaccount_signup'),
    url('^connections/$', social_views.connections, name='socialaccount_connections')
]


allauth_urls = [
    url(r"^signup/$", allauth_views.signup, name="account_signup"),
    url(r"^login/$", allauth_views.login, name="account_login"),
    url(r"^logout/$", allauth_views.logout, name="account_logout"),
    url(r"^password/change/$", allauth_views.password_change,
        name="account_change_password"),
    url(r"^email/$", allauth_views.email, name="account_email"),
    url(r"^confirm-email/$", allauth_views.email_verification_sent,
        name="account_email_verification_sent"),
    url(r"^confirm-email/(?P<key>[-:\w]+)/$", allauth_views.confirm_email,
        name="account_confirm_email"),
    url(r"^password/reset/$", allauth_views.password_reset,
        name="account_reset_password"),
    url(r"^password/reset/done/$", allauth_views.password_reset_done,
        name="account_reset_password_done"),
    url(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        allauth_views.password_reset_from_key,
        name="account_reset_password_from_key"),
    url(r"^password/reset/key/done/$", allauth_views.password_reset_from_key_done,
        name="account_reset_password_from_key_done"),
    url('^social/', include(social_urls)),
    url('^twitter/', include(twitter_urls)),
    url('^foursquare/', include(foursquare_urls)),
    url('^google/', include(google_urls)),
]

landing_urls = [
    url(
        r'^alameda-made$',
        TemplateView.as_view(template_name='landing_pages/alameda_made.html'),
        name='alameda-made',
    )
]


urlpatterns = [
    url(r'^accounts/', include(allauth_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^api/', include(api_urls)),
    url(r'^benefits$', TemplateView.as_view(template_name='pages/benefits.html'), name='benefits'),
    url(
        r'^(?P<book>\d+)/import/upload/',
        import_views.UploadImportView.as_view(),
        name='import-upload-view',
    ),
    url(r'^sign_s3/', import_views.sign_s3, name='sign-s3-view'),

    url(r'^(?P<book>\d+)/invites/add$', CreateInviteView.as_view(), name='create-invite'),
    url(r'^invites/accept/(?P<key>[\w-]+)/$', AcceptInviteView.as_view(), name='accept-invite'),
    url(r'^l/', include(landing_urls)),
    url(r"^login/$", allauth_views.login, name="login"),
    url(r'^log/email/$', email_log_view),
    url(r'^log/', include(log_urls)),
    url(r'^(?P<book>\d+)/log/', include(log_urls)),
    url(r'^nexus/', include(nexus.site.urls)),
    url(r'^policies$', TemplateView.as_view(template_name='pages/policies.html'), name='policies'),
    url(r'^pricing$', TemplateView.as_view(template_name='pages/pricing.html'), name='pricing'),
    url(r'^privacy/$', TemplateView.as_view(template_name='pages/privacy.html'), name='privacy'),
    url(r'^pay/$', PaymentView.as_view(), name='pay-view'),
    url(r'^(?P<book>\d+)/reminders/', include(reminder_urls)),
    url(r"^signup/$", allauth_views.signup, name="signup"),
    url(r'^sms/$', sms),
    url(r'^stripe/$', stripe_webhook_view),
    url(r'^tags/', include(tag_urls)),
    url(r'^(?P<book>\d+)/tags/', include(tag_urls)),
    url(r'^u/', include('profiles.urls')),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^(?P<book>\d+)/', include(contact_urls)),
    url(r'^', include('django.contrib.auth.urls')),
]

logtacts/contacts/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

class Contact(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    twitter = models.CharField(max_length=140, blank=True, null=True)
    tumblr = models.CharField(max_length=255, blank=True, null=True)
    website = models.URLField(max_length=255, blank=True, null=True)
    portfolio = models.URLField(max_length=255, blank=True, null=True)
    cell_phone = models.CharField(max_length=20, blank=True, null=True)
    home_phone = models.CharField(max_length=20, blank=True, null=True)
    notes = models.TextField(blank=True, null=True)
    tags = models.ManyToManyField('Tag',blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('contacts-view', kwargs={'pk': self.id})


class Tag(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    tag = models.CharField(max_length=100)
    color = models.CharField(max_length=20, blank=True, null=True)
    book = models.ForeignKey('Book', blank=True, null=True)

    def __unicode__(self):
        return self.tag


class Book(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=100)
    users = models.ManyToManyField(User)

    def __unicode__(self):
        return self.name


class LogEntry(models.Model):
    KIND_CHOICES = (
        ('twitter', 'Twitter'),
        ('tumblr', 'Tumblr'),
        ('facebook', 'Facebook'),
        ('email', 'Email'),
        ('in person', 'In Person'),
        ('other', 'Other'),
    )

    created = models.DateTimeField(auto_now_add=True)
    changed = models.DateTimeField(auto_now=True)
    contact = models.ForeignKey('Contact')
    kind = models.CharField(
        max_length=100,
        choices=KIND_CHOICES,
        blank=True,
        null=True,
    )
    link = models.URLField(blank=True, null=True)
    time = models.DateTimeField(blank=True, null=True)
    location = models.CharField(max_length=255, blank=True, null=True)
    logged_by = models.ForeignKey(User, blank=True, null=True, related_name='logged_by')
    notes = models.TextField(blank=True)

    def __unicode__(self):
        return "Log on %s" % (self.contact,)

contacts/views/book_views.py
import logging
from braces.views import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.contrib import messages
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.views.generic import (
    FormView,
    UpdateView,
)

from contacts.models import Book, BookOwner
from invitations.models import Invitation
import payments as payment_constants
from payments.models import StripeSubscription

from contacts.forms import BookSettingsForm
from contacts.views import BookOwnerMixin

sentry = logging.getLogger('sentry')

class BookSettingsView(LoginRequiredMixin, UpdateView):

    form_class = BookSettingsForm
    model = BookOwner
    template_name = "book_settings.html"

    def get_object(self, *args, **kwargs):
        return BookOwner.objects.get(user=self.request.user, book=self.request.current_book)

    def get_context_data(self, *args, **kwargs):
        context = super(BookSettingsView, self).get_context_data(*args, **kwargs)
        context['invitations'] = Invitation.objects.filter(book=self.request.current_book)
        context['book'] = self.request.current_book
        context['book_owners'] = self.request.current_book.owners()
        context['subscription_cost'] = "{:.2f}".format(len(self.request.current_book.owners()) * 5)
        context['stripe_subscription_cost'] = len(self.request.current_book.owners()) * 500
        context['is_book_customer'] = self.request.current_book.customer and (
            self.request.current_book.customer.user == self.request.user
        )

        return context

    def get_success_url(self):
        return reverse('book_settings', kwargs={'book': self.request.current_book.id})

    def form_valid(self, form):
        response = super(BookSettingsView, self).form_valid(form)
        self.request.current_book.name = form.cleaned_data.get('book_name')
        self.request.current_book.save()

        messages.success(self.request, "Saved!")

        return response

contacts/views/import_views.py
import boto3
import hashlib
import httplib2
import json
import logging

from allauth.socialaccount.models import SocialToken, SocialApp
from braces.views import LoginRequiredMixin
from channels import Channel
from gargoyle import gargoyle
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, JsonResponse
from django.utils import timezone
from django.views.generic import FormView, View

from contacts.forms import UploadForm
from contacts.models import Book

sentry = logging.getLogger('sentry')


class UploadImportView(LoginRequiredMixin, FormView):

    template_name = 'upload_import.html'
    form_class = UploadForm

    def get_success_url(self):
        return reverse('contacts-list', kwargs={'book': self.request.current_book.id})

    def form_invalid(self, form):
        response = super(UploadImportView, self).form_invalid(form)
        return response

    def form_valid(self, form):
        response = super(UploadImportView, self).form_valid(form)
        messages.success(self.request, "We're processing your upload. Your contacts should appear soon!")
        print(form.cleaned_data.get('upload_url'))
        Channel('process-vcard-upload').send({
            'user_id': self.request.user.id,
            'book_id': self.request.current_book.id,
            'url': form.cleaned_data.get('upload_url')
        })
        return response


def sign_s3(request):
    S3_BUCKET = 'contactotter'
    file_name = request.GET.get('file_name')
    file_type = request.GET.get('file_type')

    hashcode = hashlib.sha256(
        bytearray(str(file_name) + str(timezone.now()), 'utf-8'),
    ).hexdigest()[:6]

    file_name = hashcode + file_name

    s3 = boto3.client(
        's3',
        aws_access_key_id=settings.AWS_ACCESS_KEY,
        aws_secret_access_key=settings.AWS_SECRET_KEY,
    )

    presigned_post = s3.generate_presigned_post(
        Bucket = S3_BUCKET,
        Key = file_name,
        Fields = {"acl": "public-read", "Content-Type": file_type},
        Conditions = [
            {"acl": "public-read"},
            {"Content-Type": file_type}
        ],
        ExpiresIn = 3600
    )

    return JsonResponse({
        'data': presigned_post,
        'url': 'https://%s.s3.amazonaws.com/%s' % (S3_BUCKET, file_name)
    })

contacts/templates/base.html
{% load staticfiles %}

<html>
    <head>
        <title>Logtacts</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static "css/contacts.css" %}">
    </head>


<body>
    <nav class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url "contacts-list" %}">LOGTACTS</a>
        </div>
    </nav>
    <div class="container">
    {% block content %}
    {% endblock %}
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</body>

</html>

contacts/templates/breadcrumbs_common.html
{% load gargoyle_tags %}

{% ifswitch multi_book %}
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{% if request.current_book %}{{ request.current_book }}{% else %}Books{% endif %}<span class="caret"></span></a>
    <ul class="dropdown-menu">
        {% for book in request.books %}
        <li><a href="{{ book.get_absolute_url }}">{{ book.name }}</a></li>
        {% endfor %}
        <li role="separator" class="divider"></li>
        <li><a href="/books/new/">New</a></li>
    </ul>
</li>
{% endifswitch %}
{% if tag %}
<li><a href="{{ book.get_absolute_url }}">Contacts</a>
<li>
    <span class="label label-default" style="font-size: 80%; background-color:{{ tag.corrected_color}};">{{ tag }}</span>
</li>
{% elif reminder %}
<li><a href="{{ book.get_absolute_url }}">Contacts</a>
<li>{{ reminder }}</li>
{% elif is_search %}
<li><a href="{{ book.get_absolute_url }}">Contacts</a>
<li>
    Search{% if query %} - "{{ query }}"{% endif %}{% for search_tag in search_tags %} - <span class="label label-default" style="background-color:{{ search_tag.corrected_color}};">{{ search_tag }}</span>{% endfor %}
</li>
{% endif %}

contacts/templates/contact_list_table_item.html
{% load gravatar %}
{% load tz %}
{% load humanize %}
{% load gargoyle_tags %}
<tr>
    <td>
        <label for="id_contact_{{ contact.id }}">
            <input id="id_contact_{{ contact.id }}" name="contact_{{ contact.id }}" class="input" type="checkbox">
        </label>
    </td>
    <td>
        <a href="{{ contact.get_absolute_url }}">
            <img width="25" height="25" class="img-circle"src="{% if contact.photo_url %}{{ contact.photo_url }}{% else %}{% gravatar_url contact.preferred_email 25 %}{% endif %}">
            {{ contact.name }}
        </a>
    </td>
    <td class="hidden-sm hidden-xs">
        {% for tag in contact.tags.all|slice:":4" %}
        {% if forloop.counter0 < 3 %}
        <small><a href="{% url "contacts-tagged" pk=tag.id book=book.id %}"><span class="label label-default tag-label" style="background-color:{{ tag.corrected_color}};">{{ tag }}</span></a></small>
        {% else %}
        <a href="{{ contact.get_absolute_url }}">...</a>
        {% endif %}
        {% endfor %}
    </td>
    <td>
        <small>{% if contact.last_contact %}<span class="glyphicon glyphicon-time"></span> {{ contact.last_contact | localtime | naturaltime }}{% endif %}</small>
    </td>
    <td>
        <div class="text-right">
        {% ifnotswitch read_only_mode %}<a class="btn btn-default btn-sm" href="{% url "contacts-edit" pk=contact.pk book=book.id %}"><span class="glyphicon glyphicon-pencil"></span> Edit</a>{% endifnotswitch %}
        </div>
    </td>
</tr>

contacts/templates/contacts_add_tag.html
{% extends "base.html" %}

{% block content %}
<form action="{{ action }}" method="POST">
{% csrf_token %}
    <div class="row">
        <div class="col-md-6">
            <h2>For contacts...</h2>
            <ul>
                {% for contact in contacts %}
                <li>{{ contact.name }}</li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-6">
            <h2>Add tags...</h2>
            <ul>
                {% for tag in tags %}
                <li>
                    <label for="id_tag_{{ tag.id }}">
                        <input id="id_tag_{{ tag.id }}" name="tag_{{ tag.id }}" class="input" type="checkbox">
                        <span class="label label-default" style="background-color:{{ tag.corrected_color}};">{{ tag }}</span>
                    </label>
                </li>
                {% endfor %}
            </ul>
        </div>
        <input id="add_tag" type="submit" value="Add tags" />
    </div>
</form>
{% endblock %}

contacts/templates/delete_contact.html
{% extends "base.html" %}

{% block content %}
<ol class="breadcrumb">
    {% include "breadcrumbs_common.html" %}
    <li><a href="{{ book.get_absolute_url }}">Contacts</a>
    <li><a href="{{ contact.get_absolute_url }}">{{ contact.name }}</a></li>
    <li class="active">Delete</li>
</ol>
<h1>Delete Contact</h1>
<p>Are you sure you want to delete {{ contact }}?</p>
<form action="{% url "contacts-delete" pk=contact.id book=book.id %}" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Yes, delete." />
    <a class="btn btn-primary" href="{% url "contacts-list" book=book.id %}">No, cancel.</a>
</form>
{% endblock %}

contacts/templates/delete_log.html
{% extends "base.html" %}

{% block content %}
<ol class="breadcrumb">
    {% include "breadcrumbs_common.html" %}
    <li><a href="{{ book.get_absolute_url }}">Contacts</a>
    <li><a href="{{ logentry.contact.get_absolute_url }}">{{ logentry.contact.name }}</a></li>
    <li class="active">Delete Log</li>
</ol>
<h1>Delete Log</h1>
<p>Are you sure you want to delete the following log?</p>
<ul class="list-group">
    <li class="list-group-item">
        {% with log=logentry %}{% include "log_line.html" %}{% endwith %}
    </li>
</ul>
<form action="{% url "log-delete" pk=logentry.id book=book.id %}" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Yes, delete." />
    <a class="btn btn-primary" href="{% url "contacts-view" pk=logentry.contact.id book=book.id %}">No, cancel.</a>
</form>
{% endblock %}

contacts/templates/delete_tag.html
{% extends "base.html" %}

{% block content %}
<ol class="breadcrumb">
    {% include "breadcrumbs_common.html" %}
    <li class="active">Delete</li>
</ol>
<h1>Delete Tag</h1>
<p>Are you sure you want to delete {{ tag }}?</p>
<form action="{% url "tags-delete" pk=tag.id book=book.id %}" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Yes, delete." />
    <a class="btn btn-primary" href="{% url "contacts-list" book=book.id %}">No, cancel.</a>
</form>
{% endblock %}

contacts/templates/edit_log.html
{% extends "base.html" %}

{% block content %}

{% if logentry.id %}
<ol class="breadcrumb">
    {% include "breadcrumbs_common.html" %}
    <li><a href="{{ book.get_absolute_url }}">Contacts</a>
    <li><a href="{{ logentry.contact.get_absolute_url }}">{{ logentry.contact.name }}</a></li>
    <li class="active">Edit Log</li>
</ol>
{% else %}
<ol class="breadcrumb">
    {% include "breadcrumbs_common.html" %}
    <li><a href="{{ book.get_absolute_url }}">Contacts</a>
    <li><a href="{{ logentry.contact.get_absolute_url }}">{{ logentry.contact.name }}</a></li>
    <li class="active">Add Log</li>
</ol>
{% endif %}
<ul class="list-group">
    <li class="list-group-item">
        {% with log=logentry %}{% include "log_line.html" %}{% endwith %}
    </li>
</ul>
<form action="{{ action }}" method="POST">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <ul>
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="form-group">
        <label for="id_kind">Kind</label>
        {{ form.kind.errors }}
        {{ form.kind }}
    </div>
    <div class="form-group">
        <label for="id_link">Link</label>
        {{ form.link.errors }}
        <input class="form-control" id="id_link" maxlength="200" name="link" type="url" {% if object.link %}value="{{ object.link }}"{% endif %}/>
    </div>
    <div class="form-group">
        <label for="id_time">Date</label>
        {{ form.time.errors }}
        <input class="form-control" type="date" name="time" value="{{ logentry.display_time | date:"Y-m-d" }}" id="id_time">
    </div>
    <div class="form-group">
        <label for="id_notes">Notes</label>
        {{ form.notes.errors }}
        <textarea class="form-control" cols="40" id="id_notes" name="notes" rows="1">{% if object.notes %}{{ object.notes }}{% endif %}</textarea>
    </div>
    <input class="btn btn-primary" id="add_log" type="submit" value="Save">
</form>
{% endblock %}

contacts/templates/edit_tag.html
{% extends "base.html" %}

{% block content %}
{% if tag.id %}
<ol class="breadcrumb">
    {% include "breadcrumbs_common.html" %}
    <li><a href="{% url "contacts-tagged" pk=tag.id book=book.pk %}"><span class="label label-default" style="font-size: 80%; background-color:{{ tag.corrected_color}};">{{ tag }}</span></a>
    <li class="active">Edit</li>
</ol>
{% else %}
<ol class="breadcrumb">
    {% include "breadcrumbs_common.html" %}
    <li><a href="{{ book.get_absolute_url }}">Contacts</a>
    <li class="active">Add tag</li>
</ol>
{% endif %}
<form method="POST">
    {% csrf_token %}
    {% if form.non_field_errors %}
    <ul>
        {% for error in form.non_field_errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="form-group col-md-6">
        {{ form.tag.help_text}}
        <label for="id_tag">Tag</label>
        {{ form.tag.errors }}
        <input class="form-control" id="id_tag" maxlength="100" name="tag" type="text" {% if tag.tag %}value="{{ tag.tag }}"{% endif %}/>
    </div>
    <div class="form-group col-md-6">
        {{ form.color.help_text}}
        <label for="id_color">Color</label>
        {{ form.color.errors }}
        <input class="form-control" id="id_color" maxlength="20" name="color" type="color" {% if tag.color %}value="{{ tag.color }}"{% else %}value="#123456"{% endif %} placeholder="#123456"/>
    </div>
    <div class="col-md-6">
    <input class="btn btn-default" id="add_tag" type="submit" value="Save" />
    </div>
</form>
{% endblock %}

contacts/templates/log_list_item.html
{% if log.kind != 'edit' %}
<a href="{% url "log-edit" pk=log.id book=book.id %}"><span class="glyphicon glyphicon-pencil"></span></a>
<a href="{% url "log-delete" pk=log.id book=book.id %}"><span class="glyphicon glyphicon-trash"></span></a>
{% else %}
<span class="text-faint glyphicon glyphicon-pencil"></span>
<span class="text-faint glyphicon glyphicon-trash"></span>
{% endif %}
{% include "log_line.html" %}